name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r requrequirements.txt
        python -m pip install pyinstaller
    - name: Build
      run: pyinstaller update.py